const { type } = require("os");

const mongoose = required('mongoose');
const medicalschema = new mongoose.Schema({
    pregnancy:{type:String,max:150},
    typeOfDelivery:{type:String,max:150},
    alcohol:{type:Boolean,default:false},
    smoking:{type:Boolean,defualt:false},
    medications:{type:String,max:150},
    pregnancycomplications:{type:String, max:150},
    pregnancyType:{type:String,max:150},
    prematureMonths:{type:String,max:150},
    babyCry:{type:String,max:150},
    feedingProblem:{type:String, max:150},
    sleepProblem:{type:String, max:150},
    birthWeight:{type:String,max:150},
    birthComplication:{type:String,max:150},
    importantIllness:{type:String,max:150},
    medicalCondition:{type:String, max:150},
    consanguineousMarriageHistory:{type:String, max:150},
    history:{type:String, max:150},
    remarksVision:{type:String, max:150},
    eyeTest:{type:Boolean, defualt:false, max:150},
    useGlass:{type:Boolean, defualt:false, max:150},
    eyeProblem:{type:Boolean, defualt:false,max:150},
    remarksHearing:{type:String, max:150},
    hearingTest:{type:Boolean,default:false, max:150},
    hearingAid:{type:Boolean,defualt:false,max:150},
    earProblem:{type:Boolean, default:false,max:150},
    currentMedication:{type:String,max:150},
    previousMedication:{type:String, max:150},
    allergies:{type:String,max:150},
    actualTherapies:{type:String, max:150},
    previousTherapies:{type:String,Max:150},
    headRaise:{type:stringify,max:150},
    rollOver:{type:String, max:150},
    independentSitting:{type:String,max:150},
    walking:{type:String, max:150},
    dress:{type:String,max:150},
    spoon:{type:String,max:150},
    saidFirstWords:{type:String,max:150},
    babbling:{type:String, max:150},
    presentLanguage:{type:String,max:150},
    fingerFeeding:{type:String,max:150},
    cloudinary_id:{tyoe:String, max:150},
    file_url:{type:String, max:150}

});

const schoolschema = new mongoose.Schema({
    schoolNameAndAddress:{type:String,max:150},
    grade:{type:String,max:150},
    teacherNameDetails:{type:String,max:150},
    previousSchool:{type:String,max:150},
    generalBehaviour:{type:String,max:150},
    teacherNoted:{type:String,max:150},
    getAlongWithOthers:{type:String,max:150},
    mainSupport:{type:String,max:150},
    screenTime:{type:String,max:150},
    playInterest:{type:String,max:150}
});

const routineSchema = new mongoose.Schema({
    feedAge:{type:String, max:150},
    goodAppetite:{type:String,max:150},
    messyEater:{type:String, max:150},
    foodPreference:{type:String,max:150},
    tasteAndTexture:{type:stringify,max:150},
    canDoUpButtons:{type:String, max:150},
    canPutOnSocks:{type:String, max:150},
    canPutOnShoes:{type:String, max:150},
    toiletTrained:{type:String, max:150},
    dayAndNight:{type:String, max:150},
    toiletNight:{type:String, max:150},
    accidents:{type:String, max:150},
    toiletPaperUse:{type:String,max:150},
    managingclohting:{type:stringify,max:150},
    washingHands:{type:String,max:150},
    bathingAndBrushing:{type:String, max:150},
    toiletRemarks:{type:String,max:150},
    ageAppropriate:{type:String,max:150},
    typicalNightSleep:{type:String,max:150},
    timeOfSleep:{type:String,max:150},
    remarksSleep:{type:String,max:150},
    typicalWakeup:{type:String,max:150},
    timeOfWakeup:{type:String, max:150},
    remarksWakeup:{type:String,max:150},
    homework:{type:String,max:150},
    remarksHomework:{type:String,max:150},
    routineStrategies:{type:String, max:150},
    difficultSituation:{type:String,max:150},
    remarksChildBehaviour:{type:String,max:150},
    howYouKnowAboutUs:{type:String,max:150},

});

const clientSchema = new mongoose.Schema({
    client_ID:{type:String},
    ot:{type:Boolean,default:false},
    st:{type:Boolean,default:false},
    bt:{type:Boolean,default:false},
    cp:{type:Boolean,default:false},
    firstName:{type:String,required:true,max:150},
    emergencyNumber:{type:Number,required:true},
    email:{type:String,max:150},
    dateOfBirth:{type:Date,required:true},
    gender:{type:String,required:true,max:150},
    nationality:{type:String,max:150},
    homeLanguage:{type:String,max:150},
    familyType:{type:String,max:150},
    familyMembers:{type:Array},
    referrerDetails:{type:String,max:150},
    reason:{type:String,max:150},
    fatherName:{type:String,max:150},
    fatherMobile:{type:Number},
    fatherOccupation:{type:String,max:150},
    motherName:{type:String, max:150},
    motherMobile:{type:Number},
    motherOccupation:{type:String,max:150},
    annualIncome:{type:String,max:150},
    siblingDetails:{type:String,max:150},
    address1:{type:String,max:150},
    address2:{type:String,max:150},
    pincode:{type:Number},
    status:{type:String,defualt:'WL'},
    date:{type:Date,default:Date.now},
    remarks:{type:String},
    preferredTiming:{type:String},
    medical:medicalschema,
    school:schoolschema,
    routine:routineSchema,
});
const clientModel = mongoose.model('client',clientSchema);
module.exports = clientModel;